# -- メインメニュー --
# メインメニューはページトップのヘッダーに表示されます。
# 利用可能なパラメーターは name, pageRef, page, url, title, weight です。
# 
# 最もシンプルなメニュー設定はこちらです:
#   name = このメニューリンクに表示される名前
#   pageRef = ページやセクションのリンクに利用される識別子
#
# デフォルトでは、メニューはアルファベット順に並べられます。
# これは、 weight value で上書き可能です。
# このメニューは weight が低い値から高い値に順に表示されます。

[[main]]
  name = "ドキュメント"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "ショートコード"
  pageRef = "docs/shortcodes"
  weight = 15

[[main]]
  name = "例"
  weight = 20

[[main]]
  name = "サンプル"
  parent = "例"
  pageRef = "samples"
  weight = 16

[[main]]
  name = "ショーケース"
  parent = "例"
  pageRef = "examples"
  weight = 30

[[main]]
  name = "レシピ"
  parent = "例"
  pageRef = "guides"
  weight = 40

[[main]]
  name = "ユーザー"
  pageRef = "users"
  weight = 90

[[main]]
  name = "グッズ"
  url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
  weight = 100

#[[main]]
#  name = "テスト"
#  pageRef = "pagTest"
#  weight = 1000

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/burufugu"
  weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 400


# -- フッターメニュー --
# このフッターメニューはページ下部のコピーライト表示の前に表示されます。
# 上記のメインメニューと同様に設定できます。

 [[footer]]
   name = "タグ"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "著者"
   pageRef = "authors"
   weight = 20
